### ISSUE TITLE
[Windows] www.chefkoch.de - Anti Adblock Script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1491]
![Pic](http://i.imgur.com/03r3VzP.jpg)

I use current:
@@||js.chefkoch-cdn.de

**Comment by Alex-302** [comment]
it is clean on my end with German filter
http://i76.fastpic.ru/big/2016/0210/0b/5afdcaf569f98abaaac6bcfb088eaa0b.png

**Comment by Vincent-Michael** [comment]
maybe only germany

**Comment by Alex-302** [comment]
Checked with German VPN.
Which filters are you using?

**Comment by Vincent-Michael** [comment]
http://i.imgur.com/KeEhQ7F.png

**Comment by Alex-302** [comment]
No difference - don't see antiadblock.
You can disable Easylist and Easylist Germany, because our English and German filters include them.

Please open filtering log in Extension, enter ***js.chefkoch-cdn.de*** to the search string, select "Display blocked" and refresh the page. And copy blocked requests here. Your rule is too wide, maybe we can make it more specific.

**Comment by Vincent-Michael** [comment]
> Please open filtering log in Extension, enter js.chefkoch-cdn.de to the search string, select "Display blocked" and refresh the page. And copy blocked requests here. Your rule is too wide, maybe we can make it more specific.

No Triggers

**Comment by Alex-302** [comment]
But what excludes your rule?:)
@@||js.chefkoch-cdn.de

**Comment by Vincent-Michael** [comment]
js.chefkoch-cdn.de/js/default/userinfo/werbe-banner/vcf0d1b4ed37cbdfd8abed8f20bf6a1df.doubleclicktag.js is adblock check

**Comment by Alex-302** [comment]
Is is better to unblock one file with tag
@@||js.chefkoch-cdn.de/js/default/userinfo/werbe-banner/*.doubleclicktag.js
added to German filter
