### ISSUE TITLE
[Windows] www.windowscentral.com - false positive

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1752]
![](http://i.imgur.com/oVDl9xR.png)
http://www.windowscentral.com/

break via: "||windowscentral.com/sites/wpcentral.com/files/advagg_js"

Add:
```
windowscentral.com##a[href*="tradedoubler.com/click?"]
windowscentral.com##a[href*="shareasale.com/r.cfm?"]
windowscentral.com##a[href*="amazon.com/b?"]
windowscentral.com##a[href*="windowscentral.com/hidden-gems?"]
```
Remove:
```
||windowscentral.com/sites/wpcentral.com/files/advagg_js
windowscentral.com##a[href^="http://clkuk.tradedoubler.com/click?"]
```

Note: ads created via "var mbn_zones = { xxxx }"

**Comment by Alex-302** [comment]
Removed:
||windowscentral.com/sites/wpcentral.com/files/advagg_js
windowscentral.com##a[href^="http://clkuk.tradedoubler.com/click?"]
Added:
windowscentral.com##a[href*="shareasale.com/r.cfm?"]
windowscentral.com##a[href*="amazon.com/b?"]
windowscentral.com##a[href*="windowscentral.com/hidden-gems?"]
The first rule is unnecessary, because in English filter is generic rule:
##a[href^="https://clk.tradedoubler.com/"]
