### ISSUE TITLE
[Windows] www.giga.de - Missed Video Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/ExperimentalFilter#1812]
![](http://i.imgur.com/nF3c6nt.png)
http://www.giga.de/filme/sherlock/specials/sherlock-die-braut-des-grauens-special-im-stream-tv-ostermontag-in-der-ard/
I use current:

```
||homad-global-configs.schneevonmorgen.com.s3.amazonaws.com/www.giga.de/config.json$replace=/"enabled": true\,/"enabled": false\,/i
||homad-global-configs.schneevonmorgen.com.s3.amazonaws.com/www.giga.de/config.json$replace=/"enabled": true\,/"enabled": false\,/i,domain=giga.de
||damoh.giga.de^$replace=/(<VAST(.|\s)*?>)(.|\s)*<\/VAST>/\$1<\/VAST>/
```

**Comment by Alex-302** [comment]
added

**Comment by Vincent-Michael** [comment]
ops, i see typo (copy and past fail):

rule:
```
||homad-global-configs.schneevonmorgen.com.s3.amazonaws.com/www.giga.de/config.json$replace=/"enabled": true\,/"enabled": false\,/i,domain=giga.de
```
need replace to:
```
||s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/global_config.json$replace=/"enabled": true\,/"enabled": false\,/i,domain=giga.de
```

@Alex-302

**Comment by Alex-302** [comment]
ok

**Comment by BlazDT** [comment]
http://videos.giga.de/embed/2081387905?autoplay=1 is broken due to above "||damoh.giga.de" rules.

Exchanged them with:

||amazonaws.com/www.giga.de/config.json$replace=/"enabled": true\,/"enabled": false\,/,important
||amazonaws.com/www.giga.de/config.json$replace=/"enabled": true\,/"enabled": false\,/
