### ISSUE TITLE
com.amazon.mShop.android.shopping - can't log in

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#2008]
Can't register/log in https://play.google.com/store/apps/details?id=com.amazon.mShop.android.shopping&hl=ru

![image](https://cloud.githubusercontent.com/assets/15856304/14644878/3b962d02-065c-11e6-944c-582aaf8ebbe3.png)

**Comment by 28Black** [comment]
As I wrote in my error report, I found out that it's not related to the "experimental filters" - because adding "com.amazon.mShop.android" as an exception for Https filtering -> everything works again. So I guess you either have to look into your Https filtering module, or add the Amazon Shopping App to the exception list "out of the box".

**Comment by Alex-302** [comment]
@Revertron 
could you please check this app? It is broken by HTTPS filtering. Disabling of filters doesn't help.

**Comment by Revertron** [comment]
I was unable to determine relevant domain to whitelist. Adding the package name to exceptions.
